# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  displayName: Building & Pushing to DockerHub
  inputs:
    containerRegistry: 'DoozyRegistery'
    repository: '50307031/doozyrepository'
    command: 'buildAndPush'
    Dockerfile: './back_end/APIGateway/Dockerfile'
    buildContext: './back_end'
    tags: |
      deployment

