# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  displayName: APIGateway - Building & Pushing to DockerHub
  inputs:
    containerRegistry: 'DockerHubDoozy'
    repository: '50307031/doozyrepository'
    command: 'buildAndPush'
    Dockerfile: './back_end/APIGateway/Dockerfile'
    buildContext: './'
    tags: |
      deployment
- task: Docker@2
  displayName: PostMicroservice - Building & Pushing to DockerHub
  inputs:
    containerRegistry: 'DockerHubDoozy'
    repository: '50307031/postmicroservice'
    command: 'buildAndPush'
    Dockerfile: './back_end/PostsMicroservice/Dockerfile'
    buildContext: './'
    tags: |
      deployment
- task: Docker@2
  displayName: ProfileMicroservice - Building & Pushing to DockerHub
  inputs:
    containerRegistry: 'DockerHubDoozy'
    repository: '50307031/profilemicroservice'
    command: 'buildAndPush'
    Dockerfile: './back_end/ProfileMicroservice/Dockerfile'
    buildContext: './'
    tags: |
      deployment
