version: "3.4"

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: back_end/APIGateway/Dockerfile
    ports:
      - "6001:80"
      - "6002:443"
    networks:
        - rabbitmq_go_net
  db:
    #Pull the latest mysql image
    image: mysql:8.0.22
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3307:3306"
    #Specify where the persisted Data should be stored
    volumes:
       - dbdata:/var/lib/mysql
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: newuser
      MYSQL_PASSWORD: pass@word1234
      MYSQL_DATABASE: Usersdb

  postmicroservice:
    image: postmicroservice
    build:
      context: .
      dockerfile: back_end/PostsMicroservice/PostsMicroservice/Dockerfile
    container_name: postapi
    ports:
      - "5500:80"
    networks:
        - rabbitmq_go_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
volumes:
    dbdata: