version: "3.4"

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: back_end/APIGateway/Dockerfile
    ports:
      - "6001:80"
      - "6002:443"
    networks:
        - rabbitmq_go_net
        - db_server
  db:
   container_name: 'db'
   hostname: 'db'
   image: 'mysql'
   restart: always
   environment: 
     MYSQL_DATABASE: 'mydbname'
     MYSQL_ROOT_PASSWORD: 'mydbpd'
     MYSQL_USER: 'mydbuser'
     MYSQL_PASSWORD: 'mydbpd'
   ports: 
     - "8885:3306"
   volumes:
     - dbdata:/var/lib/mysq
   networks:
     - db_server

  postmicroservice:
    image: postmicroservice
    build:
      context: .
      dockerfile: back_end/PostsMicroservice/PostsMicroservice/Dockerfile
    container_name: postapi
    ports:
      - "5500:80"
    networks:
        - rabbitmq_go_net
        - db_server
    depends_on: 
            - db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
  db_server:
    driver: bridge
volumes:
    dbdata: