version: '3.4'

services:
  postsmicroservice:
    image: ${DOCKER_REGISTRY-}postsmicroservice:${TAG:-latest}
    build:
      context: .
      dockerfile: back_end/PostsMicroservice/PostsMicroservice/Dockerfile
    depends_on:
      - sqldata
  postsapigateway:
    image: ${DOCKER_REGISTRY-}apigateway:${TAG:-latest}
    build:
      context: .
      dockerfile: back_end/APIGateway/Dockerfile
