version: "3.4"

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: back_end/APIGateway/Dockerfile
    ports:
      - "6001:80"
      - "6002:443"

  postmicroservice:
    image: postmicroservice
    build:
      context: .
      dockerfile: back_end/PostsMicroservice/PostsMicroservice/Dockerfile
    container_name: postapi
    ports:
      - "5500:80"