# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
# This sample creates a simple InnoDB Cluster with help from the MySQL Operator.
# This yields:
#   3 MySQL Server Pods; one primary and two secondaries
#   1 MySQL Router Pod
# It uses self-signed TLS certificates.
# It requires a deployed Operator (e.g., deploy/deploy-operator.yaml),
# and requires root user credentials provided by a Kubernetes Secret;

apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: post-cluster
spec:
  secretName: mypwdspost
  instances: 3
  router:
    instances: 1
  tlsUseSelfSigned: true