apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: doozy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq
          ports:
            - containerPort: 15672
              name: rbmq-man-port
            - containerPort: 5672
              name: rbmq-mess-port

---
# make communication in the cluster possable
apiVersion: v1
kind: Service
metadata:
  name: doozy-rabbitmq
  namespace: doozy
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: rbmq-man-port
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: rbmq-mess-port
    protocol: TCP
    port: 5672
    targetPort: 5672

---
# make communication outside of cluster possable (web interface)
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer-srv
  namespace: doozy
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - name: rbmq-man-port
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: rbmq-mess-port
    protocol: TCP
    port: 5672
    targetPort: 5672